### ISSUE TITLE
when sending chat message from website (desktop) to iOS app user, I don't  get sound notifications on iOS ?

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/mobile-app-issues#16]
# Important

Please follow this template!

----------------------------------------

## What's happened?
- When sending a chat message from website (desktop) to iOS app user, I don't get sound notifications ?

...

## Steps to reproduce:
1. login as user on desktop then go to chat and send message to user using iOS app.
2. user never gets a sound notification oniOS but when user iOS user from app sends a chat message the desktop makes sound notification of message
3. 

## What's expected?

...sound should be heard on your iPhone when a user sends a chat message via website ( desktop) to iOS app user 

## OS and Devices tested
(Example: Android, iOS, iPhone, Galaxy Note...)

...iphone 11 max pro iOS 14

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos 7 php 7.3

## phpFox version
(Example: phpFox 4.6.0)
4.8.1 fresh install
...

## APIs and App version

RESTful Api 4.24
Mobile Api 4.6.2
App version from apple store - 1.7.2

## Screenshots
...

**Comment by spirogg** [comment]
Do we have to have Firebase ? 

I installed nodejs on my server but I do not have Firebase ? 

If we need Firebase. What exactly do we need ? And how much will it cost me. I don't need server on Google cloud. I want to use only my resources on my server. Is this possible ??

**Comment by spirogg** [comment]
@harrison05 all day last night and today this issue was persist

Now after 1 am CST Chicago, USA it started working by itself ? really strange

**Comment by tonyphpfox** [comment]
Hi @spirogg

First, thanks for reporting, we need more and more feedback, feature requests to improve the phpFox platform, the phpFox mobile apps to be better every day.

For your case, there are two situations
1.  Push Notification sounds: I have been tested it for both IM-Chat Messaging and ChatPlus module, both worked normally and I received the push notification with sound as expected. If your feedback is about this case, I think probably your iOS test device had turned the silent mode on. When silent mode is on, the iOS system will try to block all sound from alerts, notifications and also sound from the call no matter which applications invoke them. So please check this again.
2. The notify sound when users are actively using the mobile app and receiving new messages (not a push notification): if you mention this case, mobile app (both Android / iOS) will not play any kind of sound because we did not implement it. We think that if we play a notifying sound every time users receive a new message, it will be kind of annoying and an anti-friendly UX case for mobile users. Imagine the case that you receive 20-30 new messages per minute and you hear the beep-beep sound 20 times per minute that will be the harassment for mobile users. So we do not have any plan to implement this sound on mobile.

Regards.
