### ISSUE TITLE
when viewing the blog photos images we first upload they are cut off in feed and in blog see photos

### ISSUE THREAD

**Issue by spirogg** [PHPfox-Official/mobile-app-issues#21]
# Important

Please follow this template!

----------------------------------------

## What's happened?
after uploading the first photo for a blog, when you view the feed, it cuts off the photo and  when view the actual blog it again gets cut off?
- the only place it looks normal is when your search all blogs, the photos look normal when viewing all the blogs list, but the feed view of the blog photo and actual blog view of the photo is always cut off.
...

## Steps to reproduce:
1. go to blog on your website and click to create a blog, upload an image
2. write some text and save
3. now go to IOS App and look at the feed the photo will be cut off and click on the blog the photo is also cut off?

## What's expected?

... 
- the photo should show normal as the desktop and mobile view full photo not getting cut off

## OS and Devices tested
(Example: Android, iOS, iPhone, Galaxy Note...)

...IOS 14 iphone 11 promax 

## Server information
(Example: CentOS 7, php 7.1 apache)

...centos7 php 7.4

## phpFox version
(Example: phpFox 4.6.0)
4.8.2
...

## APIs and App version

mobile API 4.6.3
--
restful 4.24

...IOS app version 1.7.2

## Screenshots
...
 #`**mobile view and desk views are normal full photo shows**`
- 
![image](https://user-images.githubusercontent.com/17736688/99029892-4a02e780-2539-11eb-8d59-90f635d5d550.png)
![image](https://user-images.githubusercontent.com/17736688/99029904-4ff8c880-2539-11eb-8e61-7ce47e5554e8.png)
![Capture](https://user-images.githubusercontent.com/17736688/99029935-699a1000-2539-11eb-9ce9-779cdf7dd84a.PNG)
![Capture1](https://user-images.githubusercontent.com/17736688/99029936-6a32a680-2539-11eb-95b9-63e38825b5cf.PNG)

# `**here we see the list of blogs on IOS look normal also**`

![image](https://user-images.githubusercontent.com/17736688/99029961-7d457680-2539-11eb-9634-74e86bf0c682.png)

# `**But Here they Are cut Off Feed Section**`

![image](https://user-images.githubusercontent.com/17736688/99030015-9e0dcc00-2539-11eb-8294-a51ba695f805.png)
![image](https://user-images.githubusercontent.com/17736688/99030035-aa922480-2539-11eb-9409-e0d01b209c90.png)

# `**and Here is viewing the actual Blog they are cut off again**`

![image](https://user-images.githubusercontent.com/17736688/99030078-c0074e80-2539-11eb-8327-6ddda2f7ec38.png)
![image](https://user-images.githubusercontent.com/17736688/99030092-cac1e380-2539-11eb-9afc-5d617fde3277.png)

**Comment by tonyphpfox** [comment]
Hi @spirogg

I've checked your case. 
First, we want to confirm that any images, video uploads from clients (web, mobile) have not been cut off any pixels (unless end-user uploaded them from cropping feature) no matter what it came from the feed, blog or any other app modules. We store them exactly with the same dimensions as the original one.

Second, on mobile apps for the displaying image case, you saw photos in Blog Detail Screen have been cropped because we make the photo display to fill in the fixed dimensions. In this case, the fixed ratio is 16 / 9 (width/height) and this is the standard popular image ratio on the Internet for mobile devices. We had to make sure that with the unusual images with heights are so long (height > 2 widths), when coming in Item Detail Screen, end-users do not need to do the `scroll down` action to see the content of this item (happen when displaying full-height image). We did that to make the UX of the mobile app more friendly. For viewing the full-dimension image, end-users can click into the image and the new clearly image screen will push in.

Regards
