### ISSUE TITLE
Tables removed from Blog in iOS app

### ISSUE THREAD

**Issue by jwpwhite** [PHPfox-Official/mobile-app-issues#3]
## What's happened?
Tables are removed from Blog in iOS app

## Steps to reproduce:
1. Create a blog with a table on the website
2. Open the same blog in the iOS app

## What's expected?
I would not expect blogs to be removed as they are so widely used

## Browsers and Devices tested
iOS app version 1.5

## Server information
AWS Linux, php7.2

## phpFox version
phpFox 4.7.7

**Comment by spirogg** [comment]
@harrison05 @jwpwhite any update to : Can you provide some detail as to why these have been disabled and if there is a plan to support them in the future?

**Comment by spirogg** [comment]
@harrison05 I forgot @jwpwhite added this and I added it here https://github.com/PHPfox-Official/phpfox-v4-issues/issues/2964

Can you tell us when your going to get this fixed otherwise don't include blogs in IOS and Android app. 

- **This is a Big Deal for me and all of us with phpfox ultimate lic, cause if it looks like garbage how can we have this on our apps.** 

- we need to be able to get a solution 
- we can't have nice blogs and use ckeditor and then our apps blogs look like 💩💩💩💩💩💩

please do let us know what's the eta time for a solution

**you can't say its not possible** because every other website app that has a blog on there desktop website, works very well.

regards,
Spiro

**Comment by tonyphpfox** [comment]
Hi @spirogg @jwpwhite 

First, the reason why the mobile app disables these tags because these are complex HTML tags that we can not truly match 100% into native (Android/iOS) View. So for the first time, we encounter these, we simply ignore/strip these tags on mobile.

But, we think it would be better if we enabled these tags, especially tables tags in the mobile app, so we are considering a new solution for these matching. We'll implement this improvement on the mobile app as soon as possible as we can.

Regards.

**Comment by spirogg** [comment]
@tonyphpfox thank you. We really need this to work. I appreciate your feedback on this issue 

Regards,

Spiro

**Comment by jwpwhite** [comment]
Thanks @tonyphpfox, looking forward to the update :)
Kind regards
John
